### PR TITLE
Upgrade to FFmpeg 4.4

### PR DESCRIPTION
**Pull request by donavanbecker**

### CODE REVIEW

**Comment by donavanbecker** [comment]
@oznu, can you add nom_token to repo so we can push this update?

**Comment by oznu** [comment]
I don't think this has actually built an arm64 version for Mac? Rather it's just built the Intel version of the binary with the name "arm64"?

**Comment by donavanbecker** [comment]
@oznu, yes it does use the intel version, that would work for now and would use Rosetta 2, till we can get the Apple Silicon version built

**Comment by donavanbecker** [comment]
@oznu, could we upload a apple-silicon compiled ffmpeg? and add it in a release? until Apple Silicon is supported with [actions/runner](https://github.com/actions/runner/issues/805#issuecomment-744488424)?

**Review by Sunoo — APPROVED** [review]

**Comment by donavanbecker** [comment]
@oznu 

@Sunoo Is going to push a new release. Can you add the npm token so we can push to NPM

**Pull request merged**
